from fastapi.testclient import TestClient

from app.main import create_app
from app.models import Problem


def make_client(tmp_path):
    return TestClient(create_app(tmp_path / "problems"))


def login_admin(client):
    return client.post(
        "/api/auth/login",
        json={"username": "admin", "password": "admintestpassword"},
    )


def register_and_login_user(client, username: str = "alice"):
    client.post(
        "/api/users/",
        json={"username": username, "password": "password123"},
    )
    return client.post(
        "/api/auth/login",
        json={"username": username, "password": "password123"},
    )


def make_config_payload() -> dict:
    return {
        "provider_url": "https://example.com/v1/chat/completions",
        "model_name": "example-model",
        "api_key": "secret-api-key",
        "input_price_per_1k": 0.001,
        "output_price_per_1k": 0.002,
    }


def make_authoring_payload() -> dict:
    return {
        "topic": "array basics",
        "difficulty": "easy",
        "requirements": "Generate a beginner friendly problem.",
        "testcase_count": 3,
    }


def make_generated_problem() -> Problem:
    return Problem(
        id="AI_DEADLOCK",
        title="Deadlock Detection",
        description="Given lock dependency edges, determine whether a deadlock may occur.",
        input_description="The first line contains n and m. Each of the next m lines contains edge u v.",
        output_description="Output Yes if a cycle exists, otherwise output No.",
        samples=[{"input": "3 3\n1 2\n2 3\n3 1", "output": "Yes"}],
        constraints="1 <= n <= 10^5, 0 <= m <= 2 * 10^5",
        testcases=[
            {"input": "3 3\n1 2\n2 3\n3 1", "output": "Yes"},
            {"input": "3 2\n1 2\n2 3", "output": "No"},
            {"input": "2 2\n1 2\n2 1", "output": "Yes"},
        ],
        hint="Use cycle detection on a directed graph.",
        source="AI generated by external model",
        tags=["ai-generated", "graph", "deadlock"],
        difficulty="easy",
    )


def fake_external_api_post(url, json, headers, timeout):
    class FakeResponse:
        def raise_for_status(self):
            return None

        def json(self):
            return {
                "choices": [
                    {"message": {"content": make_generated_problem().model_dump_json()}},
                ],
                "usage": {
                    "prompt_tokens": 100,
                    "completion_tokens": 200,
                },
            }

    assert url == "https://example.com/v1/chat/completions"
    assert json["model"] == "example-model"
    assert headers["Authorization"] == "Bearer secret-api-key"
    return FakeResponse()


def test_admin_can_update_and_read_masked_ai_config(tmp_path):
    with make_client(tmp_path) as client:
        login_admin(client)

        update_response = client.put("/api/ai/config", json=make_config_payload())
        assert update_response.status_code == 200
        assert update_response.json()["data"]["api_key"] == "********"

        get_response = client.get("/api/ai/config")

    assert get_response.status_code == 200
    data = get_response.json()["data"]
    assert data["provider_url"] == "https://example.com/v1/chat/completions"
    assert data["model_name"] == "example-model"
    assert data["api_key"] == "********"
    assert "secret-api-key" not in get_response.text


def test_ai_config_requires_admin(tmp_path):
    with make_client(tmp_path) as client:
        assert client.get("/api/ai/config").status_code == 401

        register_and_login_user(client)

        get_response = client.get("/api/ai/config")
        update_response = client.put("/api/ai/config", json=make_config_payload())

    assert get_response.status_code == 403
    assert update_response.status_code == 403


def test_user_can_create_and_read_ai_problem_task(tmp_path, monkeypatch):
    monkeypatch.setattr("app.ai_authoring.requests.post", fake_external_api_post)

    with make_client(tmp_path) as client:
        register_and_login_user(client)

        create_response = client.post(
            "/api/ai/tasks/",
            json=make_authoring_payload(),
        )
        assert create_response.status_code == 200
        task_id = create_response.json()["data"]["task_id"]

        detail_response = client.get(f"/api/ai/tasks/{task_id}")

    assert detail_response.status_code == 200
    data = detail_response.json()["data"]
    assert data["status"] == "success"
    assert data["progress"] == 100
    assert data["result"]["id"].startswith("AI_")
    assert len(data["result"]["testcases"]) == 3
    assert data["token_usage"]["input_tokens"] > 0


def test_ai_problem_task_fails_when_model_provider_is_unavailable(tmp_path, monkeypatch):
    def unavailable_post(url, json, headers, timeout):
        raise RuntimeError(
            "model provider is unavailable; configure a reachable external API"
        )

    monkeypatch.setattr("app.ai_authoring.requests.post", unavailable_post)

    with make_client(tmp_path) as client:
        register_and_login_user(client)

        create_response = client.post(
            "/api/ai/tasks/",
            json=make_authoring_payload(),
        )
        task_id = create_response.json()["data"]["task_id"]
        detail_response = client.get(f"/api/ai/tasks/{task_id}")

    data = detail_response.json()["data"]
    assert data["status"] == "failed"
    assert data["result"] is None
    assert "model provider is unavailable" in data["error_info"]


def test_ai_problem_task_requires_login(tmp_path):
    with make_client(tmp_path) as client:
        response = client.post("/api/ai/tasks/", json=make_authoring_payload())

    assert response.status_code == 401
    assert response.json()["msg"] == "not logged in"


def test_admin_can_apply_generated_problem_to_problem_repository(tmp_path, monkeypatch):
    monkeypatch.setattr("app.ai_authoring.requests.post", fake_external_api_post)

    with make_client(tmp_path) as client:
        login_admin(client)
        create_response = client.post(
            "/api/ai/tasks/",
            json=make_authoring_payload(),
        )
        task_id = create_response.json()["data"]["task_id"]
        generated_id = client.get(f"/api/ai/tasks/{task_id}").json()["data"]["result"]["id"]

        apply_response = client.post(f"/api/ai/tasks/{task_id}/apply")
        detail_response = client.get(f"/api/problems/{generated_id}")

    assert apply_response.status_code == 200
    assert apply_response.json()["data"] == {"id": generated_id}
    assert detail_response.status_code == 200
    assert detail_response.json()["data"]["id"] == generated_id


def test_non_admin_cannot_apply_generated_problem(tmp_path, monkeypatch):
    monkeypatch.setattr("app.ai_authoring.requests.post", fake_external_api_post)

    with make_client(tmp_path) as client:
        register_and_login_user(client)
        create_response = client.post(
            "/api/ai/tasks/",
            json=make_authoring_payload(),
        )
        task_id = create_response.json()["data"]["task_id"]

        response = client.post(f"/api/ai/tasks/{task_id}/apply")

    assert response.status_code == 403
    assert response.json()["msg"] == "permission denied"


def test_user_can_cancel_pending_ai_problem_task(tmp_path, monkeypatch):
    monkeypatch.setattr("app.ai_authoring.requests.post", fake_external_api_post)

    with make_client(tmp_path) as client:
        register_and_login_user(client)
        create_response = client.post(
            "/api/ai/tasks/",
            json=make_authoring_payload(),
        )
        task_id = create_response.json()["data"]["task_id"]

        response = client.put(f"/api/ai/tasks/{task_id}/cancel")

    assert response.status_code == 400
    assert response.json()["msg"] == "task already finished"

